name = "GSDB"
uuid = "8306e1b3-ae66-4ca1-8c05-78d2506dc4f7"
authors = ["Brian D. Klahn <briandk@virginia.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
ReadStatTables = "52522f7a-9570-4e34-8ac6-c005c74d4b84"
ZipArchives = "49080126-0e18-4c2a-b176-c102e4b3760c"

[compat]
ReadStatTables = "0.3.2"
ZipArchives = "2.4.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
